const defaultTheme = require('tailwindcss/defaultTheme');
const pristineConfig = require('./pristine.config');
const negative = (scale) => {
    return Object.keys(scale).filter(key => scale[key] !== '0').reduce((negativeScale, key) => ({ ...negativeScale,
        [`-${key}`]: `-${scale[key]}`
    }), {});
};

const tailwindConfig = {
    prefix: 'pr-',
    important: false,
    separator: ':',
    theme: {
        screens: {
            ...defaultTheme.screens,
            ...pristineConfig.screens,
        },
        colors: {
            ...defaultTheme.colors,
            ...pristineConfig.colors,
        },
        spacing: {
            ...defaultTheme.spacing,
            ...pristineConfig.spacing,
        },
        backgroundColor: {
            ...defaultTheme.colors,
            ...pristineConfig.colors,
            ...pristineConfig.backgroundColor,
        },
        backgroundPosition: {
            ...defaultTheme.backgroundPosition,
            ...pristineConfig.backgroundPosition,
        },
        backgroundSize: {
            ...defaultTheme.backgroundSize,
            ...pristineConfig.backgroundSize,
        },
        borderColor: {
            ...defaultTheme.colors,
            default: defaultTheme.colors.gray['300'],
            ...pristineConfig.colors,
            ...pristineConfig.borderColor,
        },
        borderRadius: {
            ...defaultTheme.borderRadius,
            ...pristineConfig.borderRadius,
        },
        borderWidth: {
            ...defaultTheme.borderWidth,
            ...pristineConfig.borderWidth,
        },
        boxShadow: {
            ...defaultTheme.boxShadow,
            ...pristineConfig.boxShadow,
        },
        container: {
            ...defaultTheme.container,
            ...pristineConfig.container,
        },
        cursor: {
            ...defaultTheme.cursor,
            ...pristineConfig.cursor,
        },
        fill: {
            ...defaultTheme.fill,
            ...pristineConfig.fill,
        },
        flex: {
            ...defaultTheme.flex,
            ...pristineConfig.flex,
        },
        flexGrow: {
            ...defaultTheme.flexGrow,
            ...pristineConfig.flexGrow,
        },
        flexShrink: {
            ...defaultTheme.flexShrink,
            ...pristineConfig.flexShrink,
        },
        fontFamily: {
            ...defaultTheme.fontFamily,
            ...pristineConfig.fontFamily,
        },
        fontSize: {
            ...defaultTheme.fontSize,
            ...pristineConfig.fontSize,
        },
        fontWeight: {
            ...defaultTheme.fontWeight,
            ...pristineConfig.fontWeight,
        },
        height: {
            auto: 'auto',
            ...defaultTheme.spacing,
            ...pristineConfig.spacing,
            full: '100%',
            screen: '100vh',
            ...pristineConfig.height,
        },
        inset: {
            ...defaultTheme.inset,
            ...pristineConfig.inset,
        },
        letterSpacing: {
            ...defaultTheme.letterSpacing,
            ...pristineConfig.letterSpacing,
        },
        lineHeight: {
            ...defaultTheme.lineHeight,
            ...pristineConfig.lineHeight,
        },
        listStyleType: {
            ...defaultTheme.listStyleType,
            ...pristineConfig.listStyleType,
        },
        margin: {
            auto: 'auto',
            ...defaultTheme.spacing,
            ...negative({...defaultTheme.spacing}),
            ...pristineConfig.spacing,
            ...negative({...pristineConfig.spacing}),
            ...pristineConfig.margin,
            ...negative({...pristineConfig.margin}),
        },
        maxHeight: {
            ...defaultTheme.maxHeight,
            ...pristineConfig.maxHeight,
        },
        maxWidth: {
            ...defaultTheme.maxWidth,
            ...pristineConfig.maxWidth,
        },
        minHeight: {
            ...defaultTheme.minHeight,
            ...pristineConfig.minHeight,
        },
        minWidth: {
            ...defaultTheme.minWidth,
            ...pristineConfig.minWidth,
        },
        objectPosition: {
            ...defaultTheme.objectPosition,
            ...pristineConfig.objectPosition,
        },
        opacity: {
            ...defaultTheme.opacity,
            ...pristineConfig.opacity,
        },
        order: {
            ...defaultTheme.order,
            ...pristineConfig.order,
        },
        padding: {
            ...defaultTheme.spacing,
            ...pristineConfig.spacing,
            ...pristineConfig.padding,
        },
        stroke: {
            current: 'currentColor',
            ...pristineConfig.stroke,
        },
        textColor: {
            ...defaultTheme.colors,
            ...pristineConfig.colors,
            ...pristineConfig.textColor,
        },
        width: {
            auto: 'auto',
            ...defaultTheme.spacing,
            ...pristineConfig.spacing,
            '1/2': '50%',
            '1/3': '33.333333%',
            '2/3': '66.666667%',
            '1/4': '25%',
            '2/4': '50%',
            '3/4': '75%',
            '1/5': '20%',
            '2/5': '40%',
            '3/5': '60%',
            '4/5': '80%',
            '1/6': '16.666667%',
            '2/6': '33.333333%',
            '3/6': '50%',
            '4/6': '66.666667%',
            '5/6': '83.333333%',
            '1/12': '8.333333%',
            '2/12': '16.666667%',
            '3/12': '25%',
            '4/12': '33.333333%',
            '5/12': '41.666667%',
            '6/12': '50%',
            '7/12': '58.333333%',
            '8/12': '66.666667%',
            '9/12': '75%',
            '10/12': '83.333333%',
            '11/12': '91.666667%',
            full: '100%',
            screen: '100vw',
            ...pristineConfig.width,
        },
        zIndex: {
            ...defaultTheme.zIndex,
            ...pristineConfig.zIndex,
        },
    },
    variants: {
        alignContent: ['responsive'],
        alignItems: ['responsive'],
        alignSelf: ['responsive'],
        appearance: ['responsive'],
        backgroundAttachment: ['responsive'],
        backgroundColor: ['responsive', 'hover', 'focus'],
        backgroundPosition: ['responsive'],
        backgroundRepeat: ['responsive'],
        backgroundSize: ['responsive'],
        borderCollapse: ['responsive'],
        borderColor: ['responsive', 'hover', 'focus'],
        borderRadius: ['responsive'],
        borderStyle: ['responsive'],
        borderWidth: ['responsive'],
        boxShadow: ['responsive', 'hover', 'focus'],
        cursor: ['responsive'],
        display: ['responsive'],
        fill: ['responsive'],
        flex: ['responsive'],
        flexDirection: ['responsive'],
        flexGrow: ['responsive'],
        flexShrink: ['responsive'],
        flexWrap: ['responsive'],
        float: ['responsive'],
        fontFamily: ['responsive'],
        fontSize: ['responsive'],
        fontSmoothing: ['responsive'],
        fontStyle: ['responsive'],
        fontWeight: ['responsive', 'hover', 'focus'],
        height: ['responsive'],
        inset: ['responsive'],
        justifyContent: ['responsive'],
        letterSpacing: ['responsive'],
        lineHeight: ['responsive'],
        listStylePosition: ['responsive'],
        listStyleType: ['responsive'],
        margin: ['responsive'],
        maxHeight: ['responsive'],
        maxWidth: ['responsive'],
        minHeight: ['responsive'],
        minWidth: ['responsive'],
        objectFit: ['responsive'],
        objectPosition: ['responsive'],
        opacity: ['responsive'],
        order: ['responsive'],
        outline: ['responsive', 'focus'],
        overflow: ['responsive'],
        padding: ['responsive'],
        pointerEvents: ['responsive'],
        position: ['responsive'],
        resize: ['responsive'],
        stroke: ['responsive'],
        tableLayout: ['responsive'],
        textAlign: ['responsive'],
        textColor: ['responsive', 'hover', 'focus'],
        textDecoration: ['responsive', 'hover', 'focus'],
        textTransform: ['responsive'],
        userSelect: ['responsive'],
        verticalAlign: ['responsive'],
        visibility: ['responsive'],
        whitespace: ['responsive'],
        width: ['responsive'],
        wordBreak: ['responsive'],
        zIndex: ['responsive'],
    },
    corePlugins: {},
    plugins: [],
};

module.exports = tailwindConfig;
